name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write  
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman SVG(s)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move files to docs/
        run: |
          mkdir -p docs
          cp -f dist/pacman-contribution-graph.svg docs/pacman.svg
          if [ -f dist/pacman-contribution-graph-dark.svg ]; then
            cp -f dist/pacman-contribution-graph-dark.svg docs/pacman-dark.svg
          fi

      - name: Commit updated SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "chore: update pacman svg"
            file_pattern: docs/*.svg
